name: Aqua Cloud

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '15 21 * * 2'

jobs:
  build:
    name: Vulnerability Scan
    runs-on: "ubuntu-24.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          set-safe-directory: '/github/workspace'

      - name: Run Trivy vulnerability scanner against Aqua Cloud
        uses: aquasecurity/trivy-action@0.11.0
        with:
          scan-type: 'fs'
          hide-progress: true
          format: 'table'
          security-checks: 'vuln,config'
        env:
          AQUA_KEY: ${{ secrets.AQUA_KEY }}
          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
          TRIVY_RUN_AS_PLUGIN: 'aqua'

