name: Aqua Cloud

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '15 21 * * 2'

jobs:
  build:
    name: Vulnerability Scan
    runs-on: "ubuntu-24.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner against Aqua Cloud
        uses: simar7/trivy-action@fe9b9e7e3c0d9e764d9c018d5603f57fba6aba3d # refer: https://github.com/actions/runner/issues/2033
        with:
          scan-type: 'fs'
          hide-progress: true
          format: 'table'
          scanners: 'vuln,config'
        env:
          AQUA_KEY: ${{ secrets.AQUA_KEY }}
          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
          TRIVY_RUN_AS_PLUGIN: 'aqua'

